title: Mari ages just like the rest of us
content: []
github: true
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7596717271953821
  brandStrength: 1
  lightness: 0.2577292448841035
  brandColors:
    - '#000000'
    - '#606060'
    - '#A5A5A5'
    - '#FF1C00'
    - '#FDC000'
  rhythmicContrast: 0.719309534644708
typography_spectrum: 0.9066036359872669
layout_spectrum: 0.6184608940966427
name: bobspunt
description: a beachhouse birthday bash
